services:
  - type: web
    name: huggor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: GRADIO_SERVER_NAME=0.0.0.0 GRADIO_SERVER_PORT=$PORT python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: HF_TOKEN
        sync: false
